### ISSUE TITLE
ForgeGradle IDEA issues w/ partial fixes

### ISSUE THREAD

**Issue by bonii-xx** [MinecraftForge/ForgeGradle#266] opened 2015-09-13 08:32 UTC
The IDEA Project for Forge itself (setupForge) is missing the Forge src because the content root/source is set up incorrectly. The Forge src needs to be [added as a separate content root](https://www.jetbrains.com/idea/help/configuring-content-roots.html) since it's not a child of the project structure. Here is what my fixed Forge.iml looks like:
```xml
<content url="file://$MODULE_DIR$">
  <sourceFolder url="file://$MODULE_DIR$/src/main/resources" isTestSource="false" />
  <sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false" />
  <sourceFolder url="file://$MODULE_DIR$/src/main/start" isTestSource="false" />
  <excludeFolder url="file://$MODULE_DIR$/.gradle" />
  <excludeFolder url="file://$MODULE_DIR$/build" />
</content>
<content url="file://$MODULE_DIR$/../../src">
  <sourceFolder url="file://$MODULE_DIR$/../../src/main/java" isTestSource="false" />
  <sourceFolder url="file://$MODULE_DIR$/../../src/main/resources" isTestSource="false" />
  <sourceFolder url="file://$MODULE_DIR$/../../src/test/java" isTestSource="false" />
  <sourceFolder url="file://$MODULE_DIR$/../../src/test/resources" isTestSource="false" />
</content>
```

The IDEA project for mods has an incorrect dependency order. Forge is at the bottom, while it should come at the top right after the mods. This causes the log4j config to not be loaded since one of the other jars provides an incorrect one.

Furthermore the IDEA project has issues when running Minecraft, although this might not be IDEA specific. The mods in the dependencies are not getting loaded by Minecraft, although they are in the classpath. When debugging the bytecode of the forge jar seems to not match - it's impossible to set breakpoints or step through the forge/mc code. This hints at an issue with the binary jar files itself, a possible missmatch between the class files and the source provided.
Yes I've cleaned the whole stuff and refreshed the caches etc. I've tried pretty much everything but all the project specific settings seem to be correct, so I suspect it's actually an FG/setup issue.

**Comment by GirafiStudios** [comment] 2015-09-13 09:31
What version of Forge Gradle are you running?
If you're running FG 2.0, the issue you're describing with dependencies not getting loaded by Minecraft, that got fixed yesterday. So make sure you have the latest build :)

**Comment by bonii-xx** [comment] 2015-09-13 13:39
Yes! The last (and most important) issue finally works! I last tried it yesterday evening. It has prevented me from working on things for a while.

**Comment by AbrarSyed** [comment] 2015-09-13 15:44
Please make seperate issues...
1) duplicate of #224
2) duplicate of #265 
3) duplicate of #254

**Closed by AbrarSyed** 2015-09-13 15:44 UTC
