### ISSUE TITLE
Annotation processors deprecated

### ISSUE THREAD

**Issue by MinecraftPlaye** [MinecraftForge/ForgeGradle#495] opened 2018-04-18 12:27 UTC
When using newer Gradle versions like 4.6, Gradle will also throw out these warnings:

(I ran the _gradlew build_ command)

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
A more precise output for example:
```

```
> Task :compileJava
Putting annotation processors on the compile classpath has been deprecated and is scheduled to be removed in Gradle 5.0. Please add them to the processor path instead. If these processors were unintentionally leaked on the compile classpath, use the -proc:none compiler option to ignore them..
```

This here is my bare-bone buildscript for testing purposes:

```
buildscript {
    repositories {
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

task wrapper(type: Wrapper) {
	gradleVersion = '4.6'
}

apply from: 'gradle/scripts/dependencies.gradle'

version = "1.12.1-1.0.0"
group = "com.yourname.modid"
archivesBaseName = "modid"

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.1-14.22.0.2444"
    runDir = "run"
    
    mappings = "snapshot_20170804"
    makeObfSourceJar = false
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
```

**gradle/scripts/dependencies.gradle**

```
dependencies {
    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"
      
    // real examples
    //compile 'com.mod-buildcraft:buildcraft:6.0.8:dev'  // adds buildcraft to the dev env
    //compile 'com.googlecode.efficient-java-matrix-library:ejml:0.24' // adds ejml to the dev env

    // the 'provided' configuration is for optional dependencies that exist at compile-time but might not at runtime.
    //provided 'com.mod-buildcraft:buildcraft:6.0.8:dev'

    // the deobf configurations:  'deobfCompile' and 'deobfProvided' are the same as the normal compile and provided,
    // except that these dependencies get remapped to your current MCP mappings
    //deobfCompile 'com.mod-buildcraft:buildcraft:6.0.8:dev'
    //deobfProvided 'com.mod-buildcraft:buildcraft:6.0.8:dev'

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

}
```

Yeah, the buildscript is a bit older and I haven't updated all the sytanx to Gradle 4.6 there. I don't think there is any custom logic added to this buildscript here, meaning most likely the deprecation warning is coming from ForgeGradle or things it depends upon.
Within the src folder is only the normal example mod which Forge provides... nothing special there.

**Comment by LexManos** [comment] 2018-04-18 12:32
Duplicate of https://github.com/MinecraftForge/ForgeGradle/issues/493

**Closed by LexManos** 2018-04-18 12:32 UTC
