### ISSUE TITLE
useDepAts seems to look for old ATs before actually updating the dependency

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/ForgeGradle#312] opened 2015-12-19 23:35 UTC
[build.gradle](https://github.com/mezz/JEIAddons/blob/1.8/build.gradle)

Here is console output from a recent jenkins build:
https://gist.github.com/mezz/6308e4bb684acf7818e6

I am building my mod against `JEI 1.10.0.102`, which has an AT file, but it is looking for an AT from an older version, `JEI 1.8.3.99`.

```
Found AccessTransformer: jei_at.cfg_jei_1.8-1.8.3.99_at.cfg
...
:deobfMcMCPjava.io.FileNotFoundException: /var/lib/jenkins/workspace/JEI_Addons-MC1.8/build/depAts/jei_at.cfg_jei_1.8-1.8.3.99_at.cfg (No such file or directory)
```

This means I usually have to build twice in a row, half the time it seems to work fine.

**Comment by darkhax** [comment] 2016-02-28 02:52
I am experiencing the same issue on one of my projects. Glad to know I am not alone here lol I go into my issue a bit deeper [here](https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/1).

**Comment by maruohon** [comment] 2016-03-03 15:49
I have also noticed the same issue. The recent builds of my mod on a jenkins box have tried to use the AT file from the version of JEI that was as a dependency in the previous build (ie. whenever I update the JEI dependency, the build fails on the first try). (Although atm I have only seen this twice because of lack of activity on my mod lately, but anyway, both of my most recent builds have this issue, since both of those updated the JEI dependency.)

**Comment by tterrag1098** [comment] 2016-03-20 02:10
Still occuring for me http://ci.tterrag.com/job/Chisel/branch/1.9%252Fdev/5/console

That is even with --refresh-dependencies

**Comment by darkhax** [comment] 2016-05-01 06:36
I can confirm What tterrag is saying, an issue still exists.

**Comment by AbrarSyed** [comment] 2016-05-01 06:37
ugh

**Comment by UntouchedWagons** [comment] 2016-06-07 19:15
Mezz recommended I leave a polite comment in the event I find this issue annoying. Pls fix thanks.

**Comment by darkhax** [comment] 2016-10-07 02:12
Just wanted to leave another reminder that this is still an issue. Would really appreciate a fix.

**Comment by DaemonUmbra** [comment] 2020-05-28 19:53
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)

**Closed by DaemonUmbra** 2020-05-28 19:53 UTC
Labels: Bug
