### ISSUE TITLE
Issue with incorrect ClassPath for genIntelliJRuns task on SpongeForge?

### ISSUE THREAD

**Issue by sibomots** [MinecraftForge/ForgeGradle#374] opened 2016-07-06 00:55 UTC
The SpongeForge project leverages the gradle task:  "genIntelliJRuns"

The effect is that it prepares Run configurations for Client and Server with the incorrect ClassPath of module.

For Sponge it should be:
SpongeForge_java6

instead of SpongeForge.

I'm not sure where the problem lay -- in either the SpongeForge specific properties or in ForgeGradle.

Please advise if this is something to fix here, or something we can fix in the SpongeForge specific properties.  If the latter, then this is a non issue for ForgeGradle.

**Comment by kashike** [comment] 2016-07-06 06:46
Duplicate of #357, solved in #351.

**Closed** 2020-05-28 19:59 UTC
