### ISSUE TITLE
Bump required Java version to 7

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#392] opened 2016-12-03 21:39 UTC
Gradle itself [requires Java 7](https://docs.gradle.org/current/userguide/installation.html) now, so we might as well also require it.

**Comment by kashike** [comment] 2016-12-03 21:41
If a bump in to the version of Java that Forge requires changes, it should be to Java 8.

**Comment by liach** [comment] 2016-12-03 21:44
@kashike Agrees. Since Minecraft launcher has built in Java 8, bumping to Java 8 would not be too hard. The best way, though, is to wait for Minecraft to bump to Java 8.

**Comment by kenzierocks** [comment] 2016-12-03 21:44
Sorry, I didn't make myself clear. This bump is just for FG itself, not the projects that use it. Of course, this could require projects to upgrade due to the difficulty of mixing two JDKs.

**Comment by matthewprenger** [comment] 2016-12-04 02:34
AFAIK Minecraft can't even recompile on Java 6 anymore so there shouldn't be an issue bumping FG (only affecting developers) to Java7.

**Comment by LexManos** [comment] 2016-12-04 04:14
Pretty sure it can, as thats what the default MCP workspace dumps to...
Verify this before making a claim.
Also, we are not bumping to J8 requirement. 
Also what exact version of gradle bumped the java version requirements?
Links to docs is not an answer.

I am not against requiring J8 at dev time, but it must be done in a way that makes 'accidental' J8 runtime requirements difficult.

**Comment by matthewprenger** [comment] 2016-12-04 06:14
@LexManos 
> Verify this before making a claim.

Just tested and confirmed with a 1.11 mcp workspace and Java 6. It works fine with J7 and J8.
```
src/minecraft/net/minecraft/client/gui/GuiOverlayDebug.java:81: incompatible types; inferred type argument(s) java.lang.Object do not conform to bounds of type variable(s) T
found   : <T>java.util.List<java.lang.String>
required: java.util.List<java.lang.String>
        List<String> list = this.getDebugInfoRight();
```
> Also what exact version of gradle bumped the java version requirements?

Looks like it was [2.14](https://docs.gradle.org/2.14/userguide/installation.html) -> [3.0](https://docs.gradle.org/3.0/userguide/installation.html)

> but it must be done in a way that makes 'accidental' J8 runtime requirements difficult.

As long as the targetcompatibility is set to J6 the compiler should still prevent you from using new language features. The only issue I could see would be using new J7/8 libraries like NIO, but I know IntelliJ also warns you when that happens as well.

**Comment by AbrarSyed** [comment] 2016-12-04 10:33
everyone should be using this:  https://gist.github.com/AbrarSyed/9440192

**Comment by killjoy1221** [comment] 2017-06-03 07:11
We should bump it to 8 since vanilla mc uses that now.

**Comment by LexManos** [comment] 2017-06-03 08:23
Due to a lot of changes to vanilla, we've had to update Fernflower.
So for 1.12 we'll be updating the FG version, which we can force J8 with.

**Comment by killjoy1221** [comment] 2017-06-03 08:25
You're saying that like it's a bad thing 👍

**Comment by liach** [comment] 2017-12-18 20:04
What's the current status on this?

**Comment by liach** [comment] 2017-12-29 21:21
@LexManos Can you close this? The last pull #463 merged already uses Java 8 in forgegradle.

**Comment by LexManos** [comment] 2017-12-29 23:00
ya, 2.3/1.12+ requires J8 due to Fernflower changes.

**Closed by LexManos** 2017-12-29 23:00 UTC
