### ISSUE TITLE
setupDecompWorkspace doesn't work with Gradle 3.5

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/ForgeGradle#474] opened 2018-02-21 20:27 UTC
It's getting really annoying at this point, please fix this.

**Comment by Pokechu22** [comment] 2018-02-21 20:46
3.5, or 4.5?  If 4.5, this is a duplicate of #469.

**Comment by ConorTheOreo** [comment] 2018-02-21 20:47
3.5

**Comment by Pokechu22** [comment] 2018-02-21 20:48
Can you post the full build log?

**Comment by ConorTheOreo** [comment] 2018-02-21 20:49
8:28:44 PM: Executing task 'setupDecompWorkspace'...

This mapping 'stable_20' was designed for MC 1.8.8! Use at your own peril.
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:downloadClient SKIPPED
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings
:genSrgs SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:remapMcSources SKIPPED
:recompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recompileMc'.
> org.gradle.api.logging.LoggingManager.setLevel(Lorg/gradle/api/logging/LogLevel;)Lorg/gradle/api/logging/LoggingManager;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 34.509 secs
Cause: org.gradle.api.logging.LoggingManager.setLevel(Lorg/gradle/api/logging/LogLevel;)Lorg/gradle/api/logging/LoggingManager;
8:29:19 PM: Task execution finished 'setupDecompWorkspace'.

**Comment by ConorTheOreo** [comment] 2018-02-21 20:52
well to put in some context, i am trying to build a open source client called HCC which needs 3.0+ for Shadow but gradle wont setupDecompWorkspace with 3+ for some reason so i have to try with 2.9 and then go to 3.5 but 2.9 wont work or neither will 3.5 for anything

**Comment by jriwanek** [comment] 2018-04-05 13:49
#483 should fix this when it's merged.

**Comment by DaemonUmbra** [comment] 2020-05-28 20:04
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)

**Closed by DaemonUmbra** 2020-05-28 20:04 UTC
