### ISSUE TITLE
ForgeGradle incompatible with OpenJDK

### ISSUE THREAD

**Issue by xyberviri** [MinecraftForge/ForgeGradle#601] opened 2019-06-24 15:54 UTC
Im currently using OpenJDK with OpenJ9 for my JVM off AdoptOpenJDK.net, All tasks fail when using open jdk. 

i Installed mccreator and was able to build a block so i checked their console and noticed they  redistribute java jdk 1.8.0_202 with it and was able to build my environment at this point by overriding my java home. 

gradlew setupDecompWorkspace -Dorg.gradle.java.home="C:/Pylo/MCreator183/jdk"

Just wanted to report the issue because the forge documentation only calls out java 9+ as being incompatible not Java9+ and non oracle java.

**Comment by Niko-sk2x** [comment] 2019-06-24 16:01
Note that OpenJ9 is not openjdk. OpenJDK 8 will work for sure, openj9 probably isn't well tested.

**Comment by bs2609** [comment] 2019-06-24 16:43
You haven't provided enough information to make sure, but this is probably a duplicate of #595.

**Comment by LexManos** [comment] 2019-06-24 17:22
Java 9, be it OpenJDK or Hotspot is not supported by FG2.3.

**Closed as completed by LexManos** 2019-06-24 17:22 UTC
