### ISSUE TITLE
Forge 1.9 setupDecompWorkspace Error

### ISSUE THREAD

**Issue by goldenpotato76** [MinecraftForge/ForgeGradle#356] opened 2016-04-05 17:56 UTC
I keep getting an error when trying to setup forge for 1.9: http://pastebin.com/rpKUh9Nd

**Comment by kashike** [comment] 2016-04-05 18:00
Duplicate of #298

**Closed** 2016-04-05 18:00 UTC

**Comment by goldenpotato76** [comment] 2016-04-05 18:01
I can't find how to add more RAM to the gradle process.....(i am not that used with those things)

**Comment by kashike** [comment] 2016-04-05 18:09
Add this line to *USER_HOME/.gradle/gradle.propertes*: `org.gradle.jvmargs=-Xmx3G`

**Comment by goldenpotato76** [comment] 2016-04-05 18:13
Trying it now, i hopw i put gradle.propertes in the right place...(as stated above, i am not that familiar with this)

**Comment by Brian4321** [comment] 2016-04-10 14:55
How would I add this?

**Comment by Frontrider** [comment] 2016-08-20 12:06
added,the error still persists.

**Comment by LexManos** [comment] 2016-08-20 20:51
Not much we can do, you ran out fop ram, you need to give your gradle more ram.
