### ISSUE TITLE
ForgeGradle does not respect `--offline` flag

### ISSUE THREAD

**Issue by jcollard** [MinecraftForge/ForgeGradle#731] opened 2020-11-17 17:07 UTC
Gradle provides an `--offline` flag which asks that it not access the network device. However, ForgeGradle always checks for updates and pulls bug fixes. Under normal circumstances, this is great!

If no internet connection is available and the cache has a copy of ForgeGradle a build will succeed. However, if there is a timeout when contacting `files.minecraft.net:443` the entire build will fail. That is, if the network device is on but the server is not accessible then it will result in a build fail.

Below is output from running `./gradlew --offline build` on a network that blocks traffic on port `443`. Note: Turning off the network interface results in a successful build.

```
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.

Daemon will be stopped at the end of the build stopping after processing



FAILURE: Build failed with an exception.



* What went wrong:

A problem occurred configuring root project 'Advanced Quick Items'.

> Could not resolve all artifacts for configuration ':classpath'.

   > Could not resolve net.minecraftforge.gradle:ForgeGradle:3.+.

     Required by:

         project :

      > Failed to list versions for net.minecraftforge.gradle:ForgeGradle.

         > Unable to load Maven meta-data from https://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml.

            > Could not HEAD 'https://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/maven-metadata.xml'.

               > Connect to files.minecraftforge.net:443 [files.minecraftforge.net/142.44.226.189] failed: Read timed out



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.

Use '--warning-mode all' to show the individual deprecation warnings.

See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings



BUILD FAILED in 38s
```

**Comment by TheCurle** [comment] 2020-11-17 17:09
Looking into this. Thanks for the report.

**Comment by FledgeXu** [comment] 2020-11-18 06:13
I tried to capture ForgeGradle's packets when it in offline mode. 
There is the result:
https://gist.github.com/FledgeXu/8f55c2fcf5878feb058c1447f7ef3d41
![image](https://user-images.githubusercontent.com/16664654/99491762-53f87080-29a7-11eb-9f84-85ed72d56b49.png)
One of the possible reasons for this failure is in `testServerConnection`. 
https://github.com/MinecraftForge/ForgeGradle/blob/c077542cef99ffadaf19b434eddf1e676f76c612/src/common/java/net/minecraftforge/gradle/common/util/Utils.java#L521
When Gradle is offline, ForgeGradle still tried to check the connection to Forge's maven. I wonder is it necessary?
I don't think we have any reasons to keep those checks…

**Comment by FledgeXu** [comment] 2020-11-18 06:26
Btw, Could we split MCconfig functions into different tasks? If it is, that will be neat.

**Comment by FledgeXu** [comment] 2020-11-18 06:51
The second possible reason is in there:
https://github.com/MinecraftForge/ForgeGradle/blob/c077542cef99ffadaf19b434eddf1e676f76c612/src/userdev/java/net/minecraftforge/gradle/userdev/UserDevPlugin.java#L286

**Comment by LexManos** [comment] 2020-11-18 06:59
None of what you're talking about 1) Makes any sense and 2) Would cause your issue.
If you notice everything you've pointed at swallows the IOExceptions that would arise from the situation you're describing.
If you read your error you will find that it is actually GRADLE that is trying to resolve the version of FG to use. Which is done BEFORE FG is loaded!

Beyond that, your error is the generic 'something went wrong' error, you need to provide the FULL stack as you are instructed in the log.

Also, the Checks ARE necessary as they tell users if they are on broken setups.
But again, they won't do anything to you as they eat IOExceptions and let things move on.

So please, stop spamming with possible reasons without actually reading your log or trying to understand what's actually going on.

**Comment by FledgeXu** [comment] 2020-11-18 07:07
Lex, You are right. This issue is caused by Gradle trying to resolve the version of FG to use.
Sorry for spamming.
However, according to my packet capturing, FG does do internet connection when Gradle in offline mode. 
Is that normal?

**Comment by LexManos** [comment] 2020-11-18 07:10
Probably, We don't really care about offline mode as the internet is a thing that exists and is needed for FG to function.
If local data exists, and isn't outdated, then we use it.
Things will error and either be handled or populate up the stack.
If its a real issue we can address. But until then we've got more important things to care about.
However, literally everything you've provided handles offline mode just fine, and/or is not FG doing it. 
So, closing as resolved/not our problem.

**Closed as completed by LexManos** 2020-11-18 07:10 UTC

**Comment by FinnT730** [comment] 2020-11-18 07:37
So if I am allowed to add something, this all started here: https://discord.com/channels/313125603924639766/454376090362970122/778299351680155718

**Comment by jcollard** [comment] 2020-11-18 15:07
Hello, sorry if this issue caused any problems, that certainly wasn't my intent. I originally asked about this on discord out of curiosity (see Finn's link) and was asked to open an issue.

As always, thank you so much for your time and efforts!
