### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by Brian4321** [MinecraftForge/ForgeGradle#359] opened 2016-04-10 14:51 UTC
Forge version MC1.9-12.16.0.1863-1.9
Eclipse mars 2
JDK 1.8_77  or what ever is the newest version.

I'm not sure what to do about this. 
using cmdprompt to do `gradlew setupDecompWorkspace eclipse`

http://pastebin.com/DfKkyKY8
all 3000+ lines.

Edit1: Seems that there are.. other posts about this.
Edit2: After looking at #298 , I did the --refresh-dependencies and got to 56%, however, still GC overhead limit exceeded - had to use another site to paste, as it exceeded the limit pastebin has. http://pasted.co/2931452a (check around 11:13:57.005, that's when the whole thing just- stopped and shut down)
Edit3: I'm watching a tutorial, so, instead of doing the latest version, I'll start out on 1.7.10 (which did not give me this error, during installation) and go from there.

**Comment by kashike** [comment] 2016-04-10 16:00
Duplicate of #298

**Closed** 2016-04-10 17:04 UTC
