### ISSUE TITLE
setupDecompWorkspace fails

### ISSUE THREAD

**Issue by dshadowwolf** [MinecraftForge/ForgeGradle#451] opened 2017-09-25 17:06 UTC
Updated the Forge Version and Snapshot version of a project earlier today after a strange error started showing up (unable to find a symbol - never seen that happen before). As I habitually use 'clean' before 'build' I ran a 'cleanCache' to clear the cache and see if the issue was resolved. Afterwards I get an error when trying the 'setupDecompWorkspace' task to get things back on track. (setupDevWorkspace has the code unable to even build thanks to a lot of "missing symbol" errors)

Issue with "setupDecompWorkspace" is:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 24, Size: 9
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.jetbrains.java.decompiler.struct.consts.ConstantPool.<init>(ConstantPool.java:109)
        at org.jetbrains.java.decompiler.struct.StructClass.<init>(StructClass.java:84)
        at org.jetbrains.java.decompiler.struct.StructClass.<init>(StructClass.java:72)
        at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.java:159)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:100)
        at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:78)
        at org.jetbrains.java.decompiler.main.Fernflower.addAllClasspath(Fernflower.java:119)
        at org.jetbrains.java.decompiler.main.Fernflower.<init>(Fernflower.java:47)
        at org.jetbrains.java.decompiler.main.decompiler.BaseDecompiler.<init>(BaseDecompiler.java:32)
        at net.minecraftforge.gradle.tasks.fernflower.FernFlowerInvoker.runFernFlower(FernFlowerInvoker.java:64)
        at net.minecraftforge.gradle.tasks.fernflower.FernFlowerInvoker.main(FernFlowerInvoker.java:41)
:decompileMc FAILED

**Comment by dshadowwolf** [comment] 2017-09-25 17:21
Testing with the Forge MDK for 1.12 and it is going through, with several months old mappings file.  Are the mappings from SEP-2017 broken in some manner ?

**Comment by darkhax** [comment] 2017-09-25 17:25
@dshadowwolf I have had success using the `snapshot_20170919` mappings. So far I have only been able to reproduce this issue when ATs are involved.

**Comment by dshadowwolf** [comment] 2017-09-25 17:31
@darkhax I have seen the error in everything I've tried that is past 20170624 (the one in the Forge MDK) and even in projects such as MMD OreSpawn, which has no external dependencies that have AT's and has no AT's itself.

And it has:
```groovy
minecraft {
    version = "1.12-14.21.1.2443"
    runDir = "run"
    mappings = "snapshot_20170908"
//    coreMod = ""
    makeObfSourceJar = false
}
```

**Comment by darkhax** [comment] 2017-09-25 17:34
I've managed to reproduce your error using `snapshot_20170624` but only when an AT or dep with an AT is present.

**Comment by dshadowwolf** [comment] 2017-09-25 17:38
MMD OreSpawn has no external dependencies or AT's and I have seen the issue there. I'm seeing if using the Forge MDK itself as a clean, completely bare of any possible dependencies or other issues base will reproduce.

**Comment by dshadowwolf** [comment] 2017-09-25 18:11
And tested with "Additional Loot Tables" - which again, has no external dependencies and no Access Transformers. I have, however, seen that the default environment of the Forge MDK is fine - this is puzzling.

**Comment by dshadowwolf** [comment] 2017-09-25 18:53
Does not seem to be related to the snapshot at all - have tried in 'Additional Loot Tables' with snapshot_20170624 that is what the MDK has as a default and get the error, as well - the MDK can be told to use snapshot_20170925 and it works, so in this instance I'm out of ideas as to what the cause might be.

**Comment by LexManos** [comment] 2017-09-25 19:43
I am not able to reproduce this on anything that I try.
Can you provide the /build/taskLogs/decompileJar.log file.
And in that log file should be several "Adding File to context from classpath" lines.
I need the jar file the the last one of those lines points to.

**Comment by dshadowwolf** [comment] 2017-09-25 19:51
```
madman@WolfBoxTwo ~/AdditionalLootTables/build/taskLogs
$ cat decompileMc.log
INFO:  Adding File to context from classpath: D:\gradle\caches\modules-2\files-2.1\net.minecraftforge.gradle\ForgeGradle\2.3-SNAPSHOT\c0ca3511c0c97923a346071b61afd0d9c0e5b411\ForgeGradle-2.3-SNAPSHOT.jar
```

Let me see if one from BaseMetals has more...

**Comment by dshadowwolf** [comment] 2017-09-25 20:04
...and I have to say... What the hell ?

I wasn't finding the file in BaseMetals, so I ran the process again. Complained about not being able to access a log file - so I killed the entire contents of 'build' manually. Now it works. Lets try that over in OreSpawn - another place it failed before.

Okay, still happened there without removing the 'build' directory completely (shouldn't 'clean' do most of that ?), now lets see what happens when I remove the contents...

Here's a link to that small session: https://hastebin.com/agatomadec.tex

No idea at this point...

**Comment by gegy1000** [comment] 2017-09-25 20:10
I am also able to reproduce this, and getting the same output as @dshadowwolf. From what I can tell FernFlower is having issues parsing the ForgeGradle jar, which is strange. Could this be a FernFlower / ForgeFlower bug?

**Comment by CDAGaming** [comment] 2017-09-25 20:12
As seen in the issue I've made, I was also able to reproduce it also

**Comment by dshadowwolf** [comment] 2017-09-25 20:15
...this is strange - the project that first exhibited this issue has now gotten through a setupDecompWorkspace against 2485 with snapshot_20170908 (which it hadn't before) and snapshot_20170917 (randomly selected) after I deleted the entirety of 'build'.

But other projects are still showing this issue, even if I do that. I am somewhat puzzled by this and wondering if the issue might be an edge-case that I've managed to easily trigger.

**Comment by darkhax** [comment] 2017-09-25 20:15
Adding on to what you asked. There is no `decompileJar.log` but there is a `decompileMc.log` file though. The contents of this file in an errored setup is only a few lines, like Dhsadows. Here is my version of the file. ```
INFO:  Adding File to context from classpath: C:\Users\darkh\.gradle\caches\modules-2\files-2.1\net.minecraftforge.gradle\ForgeGradle\2.3-SNAPSHOT\c0ca3511c0c97923a346071b61afd0d9c0e5b411\ForgeGradle-2.3-SNAPSHOT.jar

```

**Comment by CDAGaming** [comment] 2017-09-25 20:27
Hm, I'll try what dshadow had done to see if any difference occurs

**Comment by dshadowwolf** [comment] 2017-09-25 20:31
@CDAGaming It only worked for the one project and the others I've tried it on have had the same failure.

**Comment by LexManos** [comment] 2017-09-25 20:48
We have found the issue, it's multi-part. Not the least of which is the fact that Fernflower doesn't support the new J9 constant pool entries. I'm adding support for that right now so it should stop erroring in a bit.
The other part @nallar is looking into, and that's that FG's packaging over-shades things that it shouldn't.

**Comment by darkhax** [comment] 2017-09-25 20:52
Thanks for looking into it :)

**Comment by dshadowwolf** [comment] 2017-09-25 20:53
Thanks for the hard work, @LexManos, @nallar and the rest of the team!

**Comment by LexManos** [comment] 2017-09-25 20:54
https://github.com/MinecraftForge/ForgeFlower/commit/c88442dba77d20eae0f9e6a120d52428305bbd09
Now its just a matter of it building and propagating to all of yall.

**Comment by CDAGaming** [comment] 2017-09-25 21:31
It's giving off a lot more errors on Travis during build :/

**Comment by LexManos** [comment] 2017-09-25 21:36
Sounds like a corrupt decompile, clean your gradle cache and try again.

**Comment by CDAGaming** [comment] 2017-09-25 21:44
`
:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\client\ForgeHooksClient.java:274: error: cannot find symbol
                int colour = biome.getSkyColorByTemp(biome.getFloatTemperature(pos));
                                                          ^
  symbol:   method getFloatTemperature(BlockPos)
  location: variable biome of type Biome
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\common\BiomeDictionary.java:258: error: method getTemperature in class Biome cannot be applied to given types;
            if (biome.isHighHumidity() && biome.getTemperature() >= 0.9F)
                                               ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\common\BiomeDictionary.java:266: error: method getTemperature in class Biome cannot be applied to given types;
                if (biome.getTemperature() <= 0.2f)
                         ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\common\BiomeDictionary.java:290: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.getTemperature() > 0.85f)
                 ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\common\BiomeDictionary.java:295: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.getTemperature() < 0.15f)
                 ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\common\BiomeDictionary.java:341: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.topBlock != Blocks.SAND && biome.getTemperature() >= 1.0f && biome.getRainfall() < 0.2f)
                                                  ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge-Dev\src\main\java\net\minecraftforge\registries\GameData.java:426: error: method does not override or implement a method from a supertype
            @Override public boolean isHidden() { return true; }
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
 FAILED
`
I've ran gradlew clean build, removed .gradle and build folder, but it is still erroring
Weirdly @LexManos , Travis and Self-building give off a different set of error

**Comment by dshadowwolf** [comment] 2017-09-25 21:48
@CDAGaming there have been quite a few naming changes starting after 20170917 - I'm handling those at this time myself.

**Comment by CDAGaming** [comment] 2017-09-25 21:53
Previous comment removed, as i forgot to refresh dependencies for new forgeflower

**Comment by dshadowwolf** [comment] 2017-09-25 22:10
hrm... I am not seeing that, currently - let me do a test in one of the projects that was still erroring.

Okay... Going to head to hastebin again, you're not going to like this, @LexManos...
Lots of failed patching. Have a complete "decompileMC" log for you, but it doesn't seem to show any issues...

https://hastebin.com/ewizuvejiz.coffeescript

**Comment by kashike** [comment] 2017-09-25 22:13
I get the feeling you tried to upgrade to Minecraft 1.12.x without upgrading to ForgeGradle 2.3 earlier.

**Comment by CDAGaming** [comment] 2017-09-25 22:20
For me, im just building forge to test some things :P

**Comment by dshadowwolf** [comment] 2017-09-25 22:21
@kashike Nope - have had these projects working on 1.12 for a few weeks now, this is the first real issue

**Comment by LexManos** [comment] 2017-09-25 22:22
@CDAGaming Please stop the spamming and make sure you preview your posts before committing to make sure they look good. That wall of text is crap.
As for the rest of it, yes, Thats the thing about MCP mappings there IS NO GUARANTEE that they will work with Forge. There may be name conflicts. If you get those issues try a different mapping, or go to mcpbot and fix the mapping yourself.

**Comment by dshadowwolf** [comment] 2017-09-25 22:24
@LexManos as noted, the project I have got working, right now, is in the process of getting those mappings changes integrated - nothing more than some name changes that are, in the end, logical if not, in the one case, entirely precise.

On the other hand... the issue I ran into with the setupDecompWorkspace failing with failed patches....

**Comment by CDAGaming** [comment] 2017-09-25 22:25
Lex, thats why i remove my previous post, because i missed a step to regen dependencies ;)

**Comment by LexManos** [comment] 2017-09-25 22:28
Ah found the issue, fixed in FF, try again after cleaning/refreshing in like 15 mins.

**Comment by CDAGaming** [comment] 2017-09-25 22:28
Ok, will do.

Thanks Lex

**Comment by P3pp3rF1y** [comment] 2017-09-25 22:38
Works correctly after the latest change. (I was getting the same issues that dshadowwolf reported above before the change)

**Comment by CDAGaming** [comment] 2017-09-25 22:46
Build Works now, thanks Lex

**Comment by CDAGaming** [comment] 2017-09-25 23:16
Hm, well it works on some snapshots but for the most recent ones, its giving off 8 errors

**Comment by CDAGaming** [comment] 2017-09-25 23:17
Both in travis and in self build

**Comment by dshadowwolf** [comment] 2017-09-25 23:24
Working now - had to clear the cache from an earlier try, but it is working now.

**Comment by CDAGaming** [comment] 2017-09-25 23:27
Unfortunatly, that wasn't the case for me :(

**Comment by CDAGaming** [comment] 2017-09-25 23:29
3 Errors
error: method getTemperature in class Biome cannot be applied to given types;
error: method does not override or implement a method from a supertype
error: cannot find symbol

Reference to https://travis-ci.org/CDAGaming/MinecraftForge

**Comment by LexManos** [comment] 2017-09-26 01:45
That's on you for not properly updating the mappings.
You need to know what you're doing when dealing with Forge itself.

**Comment by CDAGaming** [comment] 2017-09-26 02:01
Well, an Update on this, is that i learned one thing: DO NOT skip past 3 months when updating mappings
right now i have it working on 0908 snapshots

**Comment by dshadowwolf** [comment] 2017-09-26 15:43
@CDAGaming try "cleancache"

**Comment by CDAGaming** [comment] 2017-09-26 16:40
Another Update: It is able to build up to September 16th mappings but gives errors past it.(Sadly unable to actually test in MC bc of SpecialSource bug/Forge not launching issue)

**Comment by darkhax** [comment] 2017-09-26 18:09
@dshadowwolf I believe you can close this issue now?

**Comment by CDAGaming** [comment] 2017-09-26 18:59
@darkhax Yup you can close this, as the SpecialSource fix is now fully working for me too

**Closed** 2017-09-26 21:12 UTC
