### ISSUE TITLE
genIntellijRuns NullPointerException

### ISSUE THREAD

**Issue by mickare** [MinecraftForge/ForgeGradle#533] opened 2018-11-29 20:16 UTC
forge-1.12.2-14.23.5.2768-mdk

`./gradlew genIntellijRuns` fails to create Run configurations in Intellij Idea with a NullPointerException.

### Log:
https://pastebin.com/9pu1fN35

```
java.lang.NullPointerException
        at net.minecraftforge.gradle.common.Constants.addXml(Constants.java:297)
        at net.minecraftforge.gradle.user.UserBasePlugin.injectIntellijRuns(UserBasePlugin.java:1305)
        at net.minecraftforge.gradle.user.UserBasePlugin$14.execute(UserBasePlugin.java:1213)
        at net.minecraftforge.gradle.user.UserBasePlugin$14.execute(UserBasePlugin.java:1176)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
```
### File
https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.3/src/main/java/net/minecraftforge/gradle/common/Constants.java#L297

**Comment by ICEFIR** [comment] 2018-12-09 15:04
I am currently getting these as well, not sure where it comes from.....
It used to be just fine

**Comment by ICEFIR** [comment] 2018-12-09 15:21
Just for reference, eclipse setup still works fine

**Comment by Leevi** [comment] 2018-12-29 09:06
@mickare @ICEFIR  I got this problem solved by totally closing IDEA when running this task. 

It looks like that the problem is caused by the IDEA is locking the workspace file when it's running. So you cannot run the task in Gradle panel anymore as it's stated in 
https://mcforge.readthedocs.io/en/latest/gettingstarted/

I checked the code related and found they look fine. After I totally closed IDEA and run the task from shell, it works!

**Comment by dariusstrasel** [comment] 2018-12-30 18:54
I'm also getting this stack trace when running ```./gradlew genIntellijRuns```. 

I've tried closing IDEA and then re-running the command and consecutively clearing the Gradle cache, but neither options resolve it.

**Comment by liach** [comment] 2018-12-31 07:06
try deleting the iml file.

**Comment by dariusstrasel** [comment] 2019-01-03 00:45
Couldn't find a ```iml``` file, but deleted the whole ```.idea``` folder and was able to run ```./gradlew genIntellijRuns``` successfully. Thanks for the inspiration/help! @liach 

Might be a solution for others?

**Comment by SachsKaylee** [comment] 2019-01-03 00:54
Same error here, but deleting the .idea folder(or just deleting all files from it) throws this error:

```
patrick@PATRICK:~/Development/Sahnee/NPCs$ ./gradlew genIntellijRuns
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-3996470        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################
:genIntellijRuns
java.lang.RuntimeException: Intellij workspace file could not be found! are you sure you imported the project into intellij?
        at net.minecraftforge.gradle.user.UserBasePlugin$14.execute(UserBasePlugin.java:1207)
        at net.minecraftforge.gradle.user.UserBasePlugin$14.execute(UserBasePlugin.java:1176)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

BUILD SUCCESSFUL

Total time: 5.114 secs

patrick@PATRICK:~/Development/Sahnee/NPCs$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

```

**Comment by liach** [comment] 2019-01-03 01:18
@patricksachs do `./gradlew idea genIntellijRuns` instead. idea task will generate files for idea, which you open instead of import in intellij idea

**Comment by MattJohns** [comment] 2019-08-10 07:42
I solved it by clicking refresh icon in gradle tasks window, after running setupDecompWorkspace.

**Comment by KenCoder** [comment] 2019-08-28 02:55
I was unable to get any of the above solutions to work from the command line. But MattJohns answer worked for me:  import into IntelliJ, run setupDecompWorkspace from inside IntelliJ, then refresh gradle, then run genIntellijRuns also from inside the IntelliJ. Thanks!

**Comment by rowburt** [comment] 2019-11-15 15:26
Kept getting this error when running genIntellijRuns.
Running build/tmp/makeStart/extracted/GradleStart.java let me start forge without using the genIntellijRuns command

**Comment by Niko-sk2x** [comment] 2019-11-17 15:48
This is just what I experienced myself, on linux but in my case the issue was that intellij by itself doesn't create the empty entries in the XML for run configs anymore, and FG throws an NPE when they don't exist. Creating any dummy run configuration of type application and **then** running `genIntellijRuns` fixes it for me.

**Comment by Grauldon** [comment] 2019-12-08 18:04
> This is just what I experienced myself, on linux but in my case the issue was that intellij by itself doesn't create the empty entries in the XML for run configs anymore, and FG throws an NPE when they don't exist. Creating any dummy run configuration of type application and **then** running `genIntellijRuns` fixes it for me.

@Barteks2x 's solution solved the problem for me as well. I am running IntelliJ on Windows 10.

**Comment by oxodao** [comment] 2019-12-27 17:24
> 
> 
> This is just what I experienced myself, on linux but in my case the issue was that intellij by itself doesn't create the empty entries in the XML for run configs anymore, and FG throws an NPE when they don't exist. Creating any dummy run configuration of type application and **then** running `genIntellijRuns` fixes it for me.

Thanks! This is the correct answer.


Edit: I can't seem to import the project correctly in the latest IntelliJ. It doesn't not show the frame letting you import projects as separate module thus preventing me from setting the [project]_main module to run...

**Comment by marcioeric** [comment] 2020-04-13 13:12
> This is just what I experienced myself, on linux but in my case the issue was that intellij by itself doesn't create the empty entries in the XML for run configs anymore, and FG throws an NPE when they don't exist. Creating any dummy run configuration of type application and **then** running `genIntellijRuns` fixes it for me.

Thanks! That works!

**Comment by DaemonUmbra** [comment] 2020-04-13 14:58
FG_2.3 is out of support, if you must develop on 1.12.2 please use one of the most recent MDKs that utilizes FG_3

**Closed as completed by DaemonUmbra** 2020-04-13 14:58 UTC
