### ISSUE TITLE
Filedates bugged in jars produced by gradle

### ISSUE THREAD

**Issue by Sedridor** [MinecraftForge/ForgeGradle#358] opened 2016-04-09 20:00 UTC
All the jar files created by gradle build have their contained files and folders set to filedate 1980-01-01 0:00 modified and the created/accessed timestamps are completely missing (set to null?).
This makes it difficult to check when certain mods were released, as the downloaded jar's timestamp is set to the time of download, not the time of creation.

**Comment by AbrarSyed** [comment] 2016-04-09 20:08
@md_5 is this a side effect of he obfuscation?

**Comment by matthewprenger** [comment] 2016-04-09 20:30
Just tested with the SpecialSource lines commented out and the jar had the correct time stamps. Confirmed a SpecialSource issue. @md-5

**Comment by nallar** [comment] 2017-09-22 22:15
Caused by SpecialSource/issues/40, which has now been fixed. Will be fixed here when SpecialSource is updated.

**Comment by DaemonUmbra** [comment] 2020-05-28 19:55
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)

**Closed by DaemonUmbra** 2020-05-28 19:55 UTC
